const parquet = require('parquetjs');

// Parquet schema for shipment order data.
//  Does not include all fields. Missing attributes, shipmentIds (if order is on multiple shipments, 
//  only primary shipmentId is included), and relatedOrderIds.
const SHIPMENT_ORDER_SCHEME = new parquet.ParquetSchema({
  shipment_id: { type: 'UTF8' },
  order_id: { type: 'UTF8' },
  customer_order_id: { type: 'UTF8', optional: true  },
  order_contract_id: { type: 'UTF8', optional: true  },
  order_load_id: { type: 'UTF8', optional: true  },
  order_manufacturer_id: { type: 'UTF8', optional: true  },
  order_promotion_id: { type: 'UTF8', optional: true  },
  order_season_id: { type: 'UTF8', optional: true  },
  order_vendor_id: { type: 'UTF8', optional: true  },
  order_launch_code_id: { type: 'UTF8', optional: true  },
  freight_terms_ownership_type: { type: 'UTF8', optional: true  },
  freight_terms_payment_type: { type: 'UTF8', optional: true  },
  launch_date: { type: 'UTF8', optional: true  },
  order_id_authority: { type: 'UTF8', optional: true  },
  order_submission_date: { type: 'UTF8', optional: true  },
  order_type: { type: 'UTF8', optional: true  },
  status_code: { type: 'UTF8', optional: true  },
  status_code_date: { type: 'UTF8', optional: true  },
  subject: { type: 'UTF8', optional: true  },
  supplier_ready_date_start: { type: 'UTF8', optional: true  },
  supplier_ready_date_end: { type: 'UTF8', optional: true  },
  total_cost_currency: { type: 'UTF8', optional: true  },
  total_cost_amount: { type: 'FLOAT', optional: true  },
  total_retail_value_currency: { type: 'UTF8', optional: true  },
  total_retail_value_amount: { type: 'FLOAT', optional: true  },
  health_arrival_status_code: { type: 'UTF8' },
  health_arrival_status_duration_unit: { type: 'UTF8' },
  health_arrival_status_duration_value: { type: 'INT64', optional: true  },
  health_arrival_eta: { type: 'UTF8', optional: true  },
  vendor_id: { type: 'UTF8', optional: true  },
  vendor_supplied_id: { type: 'UTF8', optional: true  },
  vendor_location_name: { type: 'UTF8', optional: true  },
  vendor_location_address_1: { type: 'UTF8', optional: true  },
  vendor_location_address_2: { type: 'UTF8', optional: true  },
  vendor_location_address_3: { type: 'UTF8', optional: true  },
  vendor_location_state: { type: 'UTF8', optional: true  },
  vendor_location_city: { type: 'UTF8', optional: true  },
  vendor_location_postal_code: { type: 'UTF8', optional: true  },
  vendor_location_country: { type: 'UTF8', optional: true  },
  vendor_company_name: { type: 'UTF8', optional: true  },
  vendor_contact_name: { type: 'UTF8', optional: true  },
  vendor_contact_type: { type: 'UTF8', optional: true  },
  vendor_primary_contact_phone_country_code: { type: 'UTF8', optional: true  },
  vendor_primary_contact_phone: { type: 'UTF8', optional: true  },
  vendor_alt_contact_phone_country_code: { type: 'UTF8', optional: true  },
  vendor_alt_contact_phone: { type: 'UTF8', optional: true  },
  vendor_fax_contact_phone_country_code: { type: 'UTF8', optional: true  },
  vendor_fax_contact_phone: { type: 'UTF8', optional: true  },
  vendor_contact_email: { type: 'UTF8', optional: true  },
  origin_id: { type: 'UTF8', optional: true  },
  origin_supplied_id: { type: 'UTF8', optional: true  },
  origin_location_name: { type: 'UTF8', optional: true  },
  origin_location_address_1: { type: 'UTF8', optional: true  },
  origin_location_address_2: { type: 'UTF8', optional: true  },
  origin_location_address_3: { type: 'UTF8', optional: true  },
  origin_location_state: { type: 'UTF8', optional: true  },
  origin_location_city: { type: 'UTF8', optional: true  },
  origin_location_postal_code: { type: 'UTF8', optional: true  },
  origin_location_country: { type: 'UTF8', optional: true  },
  origin_company_name: { type: 'UTF8', optional: true  },
  origin_contact_name: { type: 'UTF8', optional: true  },
  origin_contact_type: { type: 'UTF8', optional: true  },
  origin_primary_contact_phone_country_code: { type: 'UTF8', optional: true  },
  origin_primary_contact_phone: { type: 'UTF8', optional: true  },
  origin_alt_contact_phone_country_code: { type: 'UTF8', optional: true  },
  origin_alt_contact_phone: { type: 'UTF8', optional: true  },
  origin_fax_contact_phone_country_code: { type: 'UTF8', optional: true  },
  origin_fax_contact_phone: { type: 'UTF8', optional: true  },
  origin_contact_email: { type: 'UTF8', optional: true  },
  original_delivery_window_start_date: { type: 'UTF8', optional: true  },
  original_delivery_window_end_date: { type: 'UTF8', optional: true  },
  destination_id: { type: 'UTF8', optional: true  },
  destination_supplied_id: { type: 'UTF8', optional: true  },
  destination_location_name: { type: 'UTF8', optional: true  },
  destination_location_address_1: { type: 'UTF8', optional: true  },
  destination_location_address_2: { type: 'UTF8', optional: true  },
  destination_location_address_3: { type: 'UTF8', optional: true  },
  destination_location_state: { type: 'UTF8', optional: true  },
  destination_location_city: { type: 'UTF8', optional: true  },
  destination_location_postal_code: { type: 'UTF8', optional: true  },
  destination_location_country: { type: 'UTF8', optional: true  },
  destination_company_name: { type: 'UTF8', optional: true  },
  destination_contact_name: { type: 'UTF8', optional: true  },
  destination_contact_type: { type: 'UTF8', optional: true  },
  destination_primary_contact_phone_country_code: { type: 'UTF8', optional: true  },
  destination_primary_contact_phone: { type: 'UTF8', optional: true  },
  destination_alt_contact_phone_country_code: { type: 'UTF8', optional: true  },
  destination_alt_contact_phone: { type: 'UTF8', optional: true  },
  destination_fax_contact_phone_country_code: { type: 'UTF8', optional: true  },
  destination_fax_contact_phone: { type: 'UTF8', optional: true  },
  destination_contact_email: { type: 'UTF8', optional: true  },
  bill_id: { type: 'UTF8', optional: true  },
  bill_supplied_id: { type: 'UTF8', optional: true  },
  bill_location_name: { type: 'UTF8', optional: true  },
  bill_location_address_1: { type: 'UTF8', optional: true  },
  bill_location_address_2: { type: 'UTF8', optional: true  },
  bill_location_address_3: { type: 'UTF8', optional: true  },
  bill_location_state: { type: 'UTF8', optional: true  },
  bill_location_city: { type: 'UTF8', optional: true  },
  bill_location_postal_code: { type: 'UTF8', optional: true  },
  bill_location_country: { type: 'UTF8', optional: true  },
  bill_company_name: { type: 'UTF8', optional: true  },
  bill_contact_name: { type: 'UTF8', optional: true  },
  bill_contact_type: { type: 'UTF8', optional: true  },
  bill_primary_contact_phone_country_code: { type: 'UTF8', optional: true  },
  bill_primary_contact_phone: { type: 'UTF8', optional: true  },
  bill_alt_contact_phone_country_code: { type: 'UTF8', optional: true  },
  bill_alt_contact_phone: { type: 'UTF8', optional: true  },
  bill_fax_contact_phone_country_code: { type: 'UTF8', optional: true  },
  bill_fax_contact_phone: { type: 'UTF8', optional: true  },
  bill_contact_email: { type: 'UTF8', optional: true  }
});

module.exports = {
  SHIPMENT_ORDER_SCHEME
};