name: Deploy to GCP

# Run this workflow every time a new commit pushed to the repository
on:
  push:
    branches: [develop, master]

jobs:
  deploy-to-stage:
    environment: Staging

    if: github.ref == 'refs/heads/develop'
    runs-on:
      labels: ${{ fromJson(vars.SELF_HOSTED_RUNNER) }}

    env:
      PROJECT_ID: ${{ vars.PROJECT_ID }}

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.CLAUD_RUN_DEPLOYER_KEY }}

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: ${{ vars.TERMINAL_VIS_RUN_SERVICE }}
          source: ${{ vars.TERMINAL_VIS_SOURCE_PATH }}

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
